package Atividade0509;

public class Apolice {
    private String name;
    private int age;
    private double awardValue;

    public Apolice() {}

    public Apolice(String name, int age, double awardValue) {
        this.name = name;
        this.age = age;
        this.awardValue = awardValue;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return age;
    }
    public void setAge(int age) {
        if(age < 0) {
            throw new IllegalArgumentException("Age must be positive");
        }
        this.age = age;
    }
    public double getAwardValue() {
        return awardValue;
    }
    public void setAwardValue(double awardValue) {
        if (awardValue < 0){
            throw new IllegalArgumentException("AwardValue must be positive"); 
        }
        this.awardValue = awardValue;
    }

    @Override
    public String toString() {
        return "Nome: " + getName() + "\nIdade: " + getAge() + "\nValor: " + getAwardValue();
    }

    public void calculateAwardValue() {
        if (getAge() >= 18 && getAge() <= 25) {
            setAwardValue(((getAwardValue() * 20) / 100));
        } 
        else if(getAge() > 25 && getAge() <= 36) {
            setAwardValue(((getAwardValue() * 15) / 100));
        }
        else if(getAge() > 36) {
            setAwardValue(((getAwardValue() * 10) / 100));
        }
    }

    public void tradeOfferDiscount(String city) {
        if (city.equalsIgnoreCase("Ilhota")) {
            setAwardValue(getAwardValue() * 0.95);
        }
        else if (city.equalsIgnoreCase("Blumenau")){
            setAwardValue(getAwardValue() * 0.97);
        }
        else if(city.equalsIgnoreCase("Itajaí")) {
            setAwardValue(getAwardValue() * 0.99);
        }
        else if (city.equalsIgnoreCase("Hiroshima") || city.equalsIgnoreCase("Nagasaki")) {
            setAwardValue(getAwardValue() * 0.000001);
            System.out.println("Good to know that you have an acount, cause your city is very safe to live");
            System.out.println("                                                                                       ..         ..  .............................'...''''',''',,,,,,',,,,'',,,,,,''','''',,,,,,,,,,,,,;;;,,,,,,,,,;;;;;,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,,,,,,,''''',,,,,'''',,,,,,,,,,,,,,,;,,,;,,,;;;;,,,,,,;;;;;;;;;;;;;;::\r\n" + //
                    "                                                                                       ..          .............................'''.''''''',,,,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;,,,,,,,,,,;;;,,,,,,;;;;;;,,;;;;;;;;;,,,,,,,,,,,;;;;,,,,,,,,,,'''',,,,,,''',,,,,,,,,,,,;,,;,,;;;,,,;;;;,;;;;;;;;;;:::::;;;;:\r\n" + //
                    "                                                                                          ............................''''''''''''',,,,,,''',,,,,;,;;,,,,,,,,,,,,,;,,,;;;;;;;;;;;;;;;;;,;;;;;;;;;;;;;;:::;;;;;;;;;;;;;;;;;;,,,,,;;,,,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,;,,,,,;;;;;;;;;,;;::::::::::::\r\n" + //
                    "                                                                                     ..  ........................''''''''''',,,,,,,,,,,,,,,,,,,;::;;::;;;;;;codollc:::;;;;;;;;;;;;;;:cc:;;;;;;;;;;;;;;::::::::;;;;;;;;;;;;;;;;;;;;,,;;;;,,;;;;,,,,;;,,;,,,,,,,,;;;;;;;;;;;,,,,,,;;;;;;;;;;;;;;;;;;;::::::::c\r\n" + //
                    "                                                                                     .........................'''',,,,',''''',,,,,,,,,,;;;;coxkk0K00000OOO00XNWWNNXXX0kdolcc:;;:codkKXKOo:;;;;;;;;;;;;;:::::::;;::;;;;;;;;;;;;;;;;;;;;;;;,;;;;;,,;;;;;;;;;;;;;;;;;;;;;,,,;,,,,,,;;;;;;;;;;;;;;;;;;;;::::::::\r\n" + //
                    "                                                                                  .........................,;;,,,,,,,;;:clllloddoollokO0000XWMMWMMWWMMMMWWWWWMMMMMMMMWWWNNXKOkk0NWWWWMMWN0kdddxxxdollc::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,;::;;;;;;;;;;;;;;;;;::::\r\n" + //
                    "                                                                                  ................,:lllldkO0KK0000OOO0KXNNNNWWWWWWNNWWMWWMMMMWWWWMWWMWWWWWWWWWWMWWMMWWWMMMMMMWWMMMWMMMMMWWWWWWWWWWNNX0d:;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;;;;;;;;;;;;;;;,,,,,,,,,:cc;;;;;;;;;;;;;;;;;;;;;\r\n" + //
                    "                                                                                  ...........'':d0KXNWNWWWWWWWWWMMMMMMMWWWWWMWWMMWWWMMMWWWWWMMMMMWWWWNNNWWWWNNNNWWWWWWWMMWWWWWMMMMWMMWWWMMMWWMMMWWMWWWXxloxOOxoc:;;;;;:;;;;;;;;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;;;,,,,,,,,,,;::c:;,;;;;;;;,,,;;;;;;\r\n" + //
                    "                                                                                   ........:x0KNWWNNWWWWNNNWWWMMMWWWWMWWWMMMMWMWWMMWMMMWWNWWWWMMWWWWWWWWWWMWWWWNXXNNNWWWWWWNNWWWWWWWMMMMWWWWMMMMWWWWWWWNNNWWWWNXOxdoc:::;;;::;;;;;;,;;;;;;;;;;;,,,,,;;;;;;;;,,,'''',,,,,,,,,,,,,,,,,,,,;;,,,;;;;;;;;,,,,,,,;\r\n" + //
                    "                                                                                   .':oddxOKWWWWWWWWWWNNNNNNWWMWWWNNWWWWWWWWWWWWWWNWWWWNNXXNWWMMWWWWWWWWMMWNNWWWNNNNWWWWWNXKKXXXNWWWWMMWWWWMMMWWWNNNNWWWWMMMWWWWWWNNK000OOOOOxo:;;;;;;;;;;;;;,,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',,,,,,,;;;,,,,;;;;;;;;,,,;;;\r\n" + //
                    "                                                                                 .:d0NWWWWWWWWNWWWNNXXNNXNNWWWWWNNNNWNNNNNWWWWNNXKKKXXXXXKKXNWWWWNNNNNNNNWNXXXNWWWWWWWWWNXXXXNNNNNWWWWWWWWWWWWWWNNNNNWWWWMMMMMWWMMWWWWMWWWWMWWXOo;;;;;;;;;;;;;;,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,,,,;;;;;;;;;;;;;\r\n" + //
                    "                                                                               .'dXWWNWWWWWWWNNNNXXKKKKXXNNNNXNNNNNNNXNNXNNWNXK00OkkOOO00000XNNNWNXKKKKKKKKKXXNNWWWWNNNNXXNNNNNNNNNNWWWWWWWWWWWWNWWWWWMMMMMMMMWWWWMWWWWWWWWWWNNNKo;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;:;;;;;;\r\n" + //
                    "                                                                             .,o0XWWWWNNNWWWWNXK0000000KXXNXXXXKKXNWNXNNNNNNX0OOkxddddxkOOO00KXNWNK0OkkkOOOOKXXXNNXXKKK0KXXNXK0000KXNNWWWWWWMMMWWWMMWMMMMWWWWWWWWWWWNNWWWWWWWWNNNXOdl:;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,,,;;;;,,,,\r\n" + //
                    "                                                                           .:kKXNNWWWNNNNWWWWNK0kkkOO00KXNNK00OOKXWWNNWNNWNXKOkkxxxdooodk0K000KNNX0kxdddxk0XXNNXXNNX0Okkkkkkxxxxxxk0KXNWWWWWWWWMMMMWNWWWWNNNXNXXXXXNXXNWWMMMMWWWWWWWNKko:;;,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,,,,,,,,,,,,,,,,,,;;;;;,,,,,,,,,,,,,\r\n" + //
                    "                                                                         .;oKNWWNNWWNNXXXXNNNKOxddxkO0KKXNNK0OkOXNNNNNNWWWWNKkxooddoooodxkOOOOKXXK0kdoooox0KKKXNWWX0kdooodxddoooddxkO0KNNNNNNWMMMWWNXXNNXXXKKKKKKKKXKKXNWWWMMWWWMMMWWWWXOdoc;,,,''',,,,,,,,,,,,,,,,,,,,,,,,,,'',,,,,,,,,,,;;,;;,,,,,,,,,;;;;\r\n" + //
                    "                                                                       .cONNXNXXNNNNNNXK0KNNKOkkkkO0KXXNNNXKOkkKNNXXNNNNNNNK0xolccllllooodxxxkOKKOkxdooddxxxxxO0K0Okxoox0KXXKkolodxkkO0KXXXXNWWWWWNXK0KK00000OOO00OO00KXNNWWWWWWWMMMMWWWWWNKo;,,'''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''',,,,,,,,,,,,,,,,,,,,,\r\n" + //
                    "                                                                       'kNNXXXXXNNNNWNNK0KKK0OKXXXNNNNNNNXKOxk0XXKKXNNNKO00Oxxolccccccllloooddk00kxdddddddddddddddddooodO0000xoloodxxxxOO00KNNXXNNX0000OOkkkxdx0XX0O0XXNNNNWWWWWWWMMWWWWWWNNKo,','''''',,,,,,,,,'',,''''',,,,,,,,''''''''''''',,,,,,,,,,,,,,\r\n" + //
                    "                                                                      .lKNXXXXXXNNNNNXK00XXXKKXKK000KNNNNXKkdkKK0OO000OkxxxdddollccccccllloooooxxdooooooddooloollllldxolodddoooooooddodxO000XNK000kxkkkxxxxddxOKK0O0KXNNNNNWWWMWWWWWWWWWWWNNN0o;,''''',,,,,'''',,,,,'''',,,,,,,,''''''''','''',''',,,,,,,,,,\r\n" + //
                    "                                                                     ,xKNNXXK0KXNXXXK00KXNNNXXKOkxxxOKX0OOOxdkOkxdxkkkxddoooddlllllccccccllollllooooooooooolllllccclooloolllooooooooolodxkO0KKOkxxdddxxooooooodxxddkO00KKXNWWWWWWWWWWWWWMWWWWWX0o,'',,''',,''''''',''''''',,,,,'''''''''','''',,'',,,,,,,,,,\r\n" + //
                    "                                                                    .dXNXKOxxk0K0O00OO0XXXK00Okxoooodxxddddooddddoooddoodxxxxdollllllllllllllllllooooooollollllccccllcoxdollllloooolllloodk00kxdooooooolcllllllllloxOKKOO0KXNNNNWWWWNNNNWWWWNXNN0o;''''',,,,,'''',,,,''''''''''''''''''''''''''''',,,'''''',\r\n" + //
                    "                                                                .:ccdKNNKkddook0OkxxxkOKKK00kxdolcclloooooollokkdolllooooddooolllcllllllllllllllloooooollllooolllcccccoooolllcclclllcccllldkxdoooooolollccccccccclokKNKOxxxOKXXXNNNXNXXKXXXXXKKKXX0kl,'',,,'''''',,,,'''''''''''''''''''''''''''''',''''''''\r\n" + //
                    "                                                               .cKNXNNNKOdollx0K0kdoodxO000Oxollccccclllllllld00kolllloooollllllllllllccloolllolllooooollcllodollcclloooooollccccclccclcccloooooooollllllccc:::ccclodxdoolodk0KKXXNXK000KXX0OO0KXNWN0l'',,,'',,,,,,,,,,,,,,,,,,,,''''''''''''',,'',,,'''''''\r\n" + //
                    "                                                               .dXNXNNN0dlcclkXXKkoolodkOOOkdllcc::ccclllllldO0Oxolllllooooooolllllooooloodoooooloooooolllloodoollllooooooooollcccccclllccllloooooolllllccccc::ccccclllccllloxkO0KK000OkO00kxkO00KXXKd;,,,,,,,,,,,,,,,,,,'',,,,,,,''''''''''''''''''''''''''\r\n" + //
                    "                                                               ;OKXXXXKkdlc:lxOOkdolllldxkkxdolccccccclllllodkkxooolllloodxddooooloooooodddddooolloooddooooooooooooooooooooooolllcccccllllllooooooolllllcccccccccccc::cccclclodxk000OOkxdddooddddxOOOkl,',,,,,,,,,,,,'''''''',,,'''''''''''.''''''''''''''''\r\n" + //
                    "                                                               ;xkkO000Oxlccldxxollllcllodddollccclccclllllooddoollllllloxxxxdddooooooooodddooollllodddddddddddoddooodoooooooolllcccccllllllooooollccccccccccccccccccc:cccc:cllodkOOxdooolllllllloxkkxl;''''''''''''''''''''''''''''''''''''''''''''''''''''\r\n" + //
                    "                                                               .;ooodxkkdlccclllllllcclllllloooolllllcclllcloddooooooollodxxxdddooodddddoddddddoolloddddddddddddddoooooooooooolllllllllllooooooolllc:ccccclccccccllccccc:::::cclldxxdoolllccccccccokkl;,'''''''''''''''''''''''''''''''''''''''''''''''''...\r\n" + //
                    "                                                                'clcllllcccccccccllccccclclloddoooollllcccccclodxxdddoollodxxxxdddddddooooodddoolloodxxxxxxxxxxkxdoolllloooooollcclllllllooollllllccccclllllllcccccc:::::::::::cokkdlccccccccc:::ccll:,,'''''''''''''''''''..''''....''....''''''''''.......\r\n" + //
                    "                                                            ..  .,;;:::c:::::ccccllcccllllllooooooooolllcccclllodxxxdddolllodxxddddddoollllooooooloodxxxkkkkkxxxxdolllcllllllllccccllllllllllcclllcccccccccccccccccc:::::::::::cdkkdcccccccccc:::::::;,''''''''''''''''''''''''''..''''''''''''''''''...''''\r\n" + //
                    "                                                       ...........';;;;;;;;;;::ccllllllllllllllooooollllccclloooodxxxdoooolloodddooooolooooooooooooodxxkkxxxxxxxddolllllllccllllllcccccccccccc::ccc:::::ccccccllcccc::::::::::::clcc:::::ccc:::;;::;;,,,,,,,,,,,,',,,,,,'''',,''''',''',,,,,''''''''''''''''\r\n" + //
                    "                                                          ........',,,,,,;;;;;::cccllloooooollllllllcccccccllllooooddoolllllllllloooollodxxdddolllloodxxkxdddddddollcccccccclollllccccc::::::::;:::;::ccccclcclcc::::::;;:::::c:::::::::::::;;;;;;:;;,,,,,,,,,,,,,,''',,,'',,,''''''''''''''''',,'''''''''''\r\n" + //
                    "                                                                ..'',,,,,,,;;;::ccccclllllooolllllllllllllllccllllllllllllllcccccllllllloddddollloooodddxxddooollcccc:c:::cccllllcccc:::::::::::;;;;::cccccccccc:::;:::;;;:::::::::ccc:::::;;;;;::;;,,,,,,,,,,,,,,,,,,,,,'',,,,,'''''',,,,,,'',,,,,',,''''''\r\n" + //
                    "                                                        ...........';;;;;;;;;;;::::ccccclllllllllllooooolllllllllllloolllcccccccccccclllloooooodddddddddddddooooollllcccccccccccllccc:::::::::;;;;;;;;::::cccccc::;;:::;;;;::::::::::c::::;;;;;;;;;,,'',,,,,,,,,,,,,,,,'''''''''''''''''',,''',,,'''''''''''\r\n" + //
                    "                                                           .........';;;;;;;;;;::::ccccccccclllllllllooooooollllllloollcccccccccccclllllllloooddddddddddddddollooolllcccccccclllllccccccc::::::;;:;;;;::::::ccc::;;;;:::;;;:::::::::::::;;;;;;;;,,,''''',',,,,,,,,,,,,''''''''''''''''''''''''',''''''''''''\r\n" + //
                    "                                                           ..........';:::::;;::::::ccccc::ccccclllllllloooolllllooooollccccccccccclllllllooooooooooooodooollccclcccccccccccllllllllcccc:cccccccccc::::::::cccc:::;;::::::::::::::::::;;;;;;;;;,,,''''''',,,,,,,,'',,,,,''''''''''''''''''''''''''''''''''''\r\n" + //
                    "                                                        ..............,;:;:::;::::::ccc:::ccccccllllllllllllllllllloooooollllccccccccclllooooooooooooddoolllllcc:::::::::::ccllllllllllccllllllccccc::::::::c::;;::::::::::::::::::;;;;,,,,,,,,,'''',,'''',,,,'''''',,,'''''''''''''''',''''''''''''''''....\r\n" + //
                    "                                                       .................',;;::::c::::::::::ccccccccllcccccccccllllllllllcclllccccccccccllloooooooooooodooooooollc::;;;;;;;;;:cllollllllllllllccccccccc:::::::::::;;:::::::;;;;::;;;;;;;,,,,,,,,,,,''''''''''',,,,''''''''''''''''''..'''''''''''''''''......\r\n" + //
                    "                                             ..   ........................',;:cccc::;;::::::::::cccccc:::cccccccccccccccccccccccccccllllloolloooooooooooddddddolcccc::;;;;;;;:cllllllllllllllcccccccccc:::::::::::;;;::;;;;;;;;;;;;;;;;,,,,,,,,,,,,,''''',,,,,,,,'''''''''''''''''''''''''''''''''''''......\r\n" + //
                    "                                             ...............................',;:::;;;;;;;:::::::::::::::::::::::::ccccllllolllllccclllllllllllllloooooooooddoollcccccc::::::::ccllllllllllllllllcc:::::;;;;:;;;::;:::::;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,',,,,,,,,,,'''',,,,,'''',,,''''''''''''''''''''..''''.\r\n" + //
                    "                                       ...   .................................'',,;;;;;;;;;;;;;:::::::;;;;;;;:::cclllllooolllllllllllllllllllllollooooooooooollllccccccccc:::cccllllllllllllcccc:::;;:;;;;;;;;;;;;;;::::::;;;;;;,,,,,,,''''''''''''''''',,,,,,,,,,''',,''''''''''''''''''''''''''''''..'''..\r\n" + //
                    "                                  .   .....................................''''',,,,,,,,;;;;;;;;;:::::::::::::cclooollloooolllooooollllllclllllooooollloollloooolllllcccc:::::ccllcclllllllllccc::::::::::;;;;;;;;;;;;;;;;;;,,,,,,,,,'',,,'''',''''''''''',,,,,'''''''''''''''''''''''''''''''''''''''''''..\r\n" + //
                    "                      .     ... .......................................'''''''',,''',,,,;;;;;;;;;:::::::::cccllloooooooooooooodoooooollllllloooooooollloooolloooolllllccccc:cccccccllllllllllcccc::::::::;;;;;;;;;;;,,,,;;,,,,,''''','',,,,,,,,,,,,'',,,,,,,,',,'''''''''''''''''''''''''''''''.....'''''...\r\n" + //
                    "                      ..............................................'''''','',,,,,,;;;;;;;;;;;;:::::::::ccllllllooooooodddoooooooooooolllooodddoollllooooooolooooollllllllllccccccclllllllllccc:cc::::::;;;;;;;;;;;;,,,,,,'''''''''''',,,,,,,,,,,,,,',,,,,,,,,,,,,,''''',,,,''''''''''''''''''''.''''''''..'\r\n" + //
                    "         .    ..   .............................................'''''',,,,,,,,,,;;;;;;;;;;;;;;:::ccccccccllllllllooooooooooooooodooodoooodddddooollllooooooooooooollllllllccc:ccccccclllllcccccc:::::;;;;;;;;,,,,,,,,,,''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''''''''''\r\n" + //
                    "..........................................................'''''''',,,,,,;;;;;,;;;;;;;;;;;;;;:::::cclcccccccclllllooollllloooooddddxdddddddddoooolloooooodddoooooooollllllccc:::cc::cclllccccccccc::::;;;;;;;,,,,,,,,,,,'','''''''''...''',,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''''''''''''''''''''''\r\n" + //
                    "..............................................'....''''''',,,,,,,,,,,,;;;;;;;;;;;;;;;;;;:::::ccccclllccccllcclloooollllloooooddddddddddddddoooooolloodddddddooooollllllllccc:::::::ccllccccccc:ccc:::;;;,,,,,,,,,,,,,,'',,'',,'''.........',;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''\r\n" + //
                    "............................................'''''''''''''',,,,,,,,,,;;;;;::::::::::::::::cccccllllllccllllllllloooooolloooddoddddddddddooooooooooooooooddddooooolllllllcccc::::::::ccccllcccc:::cc::;;;,,,,,,,,,,,,,,,'',,'''''''..........';::;;;;;;;,,,;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,''',,,'''''''''\r\n" + //
                    "...................................'''''...''''''''''''',,,,,,,;;;;;;;;;::::::::cc:::ccccccccllllllllllllooooooodddooooodddddddddddddddooooooooooooooooodddddooolllllllcccc:::::::::ccccccc:::::::;;;;;;,,,,,,,,,,,,,''''''''''''''''',,,,',;;;;;;;;,,;;;;;;;;;;;;;,;;;;;;;;;;;,;;;,,,,,,,,,,,,,,,,,,,,,,',,\r\n" + //
                    "...........................''''''''''''''''''''',,,,,,,,,;;,,,;;;;;;;::::ccccccccccccccccccccllllllllllllloooooodddddddddddddddddoooodoooooooodddoodddddddddoolllllllllcccc::::::;;;::cccccc:::c::;;;;;,,,,,,,,,,,,,,''''''''''''''',,;;:::::;;;;;;;;;;;;;;;,,,;;,,,,;;;;;;;;;;;;;;,,,,,,,,,,;;,,,,,,,'''',,\r\n" + //
                    "..................''''''''''''''''''''''',,,,,,,,,,,,;;;;;;;;;;::::::::cccccccllllcclllllccllllooollllllclllooooodddooddddddddddooooooooooooooooddddoddddddoolllllllllllccc:::;;;;;;;;:ccccccccc:::;;;;;,,,,,;;,,;,,,''''''''''...'',,,;;:::::;::;:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,;;;,,,,,,,',,,\r\n" + //
                    ".......'''......''''''''''''',,,,,',,,,,,,,,,,,,,,,;;;;;;;:;;::::::::cccccccccllllllolloolloloooolcccclllllllllooodddddddoddddddooooooooooooooodddddddddddoooolllllllllllccc::;;;;;;;;;:::cccccc:::::;;;;;;;;;;;;,,,,,''''''''''..''',;::cc::::::::::::::::::::;;;;;;;;::::::;;;;;;;;;;;,,,,,;;;,,,,,,,,,,,,\r\n" + //
                    ".'''.''''''''''''''','',,,,,,,,,,,,,,;;;;;;;,,;;;;;;;;;;::::::::cccccclllllllllloooooooddoooooddollccclllllllllllooddddddddddddddddddddddddxxxxxxdddddddooooooooloooolllllccc:::;;;;;;;;;;:cccc:::::::::;;;;;;;;;;,,,,,,,''''''',,,,,;:cccccccc::cccccccc::::::::::::::::::::::::;;;;;;;;;;;;::;;;;;,,,,,,,,\r\n" + //
                    "''''''''''''''',,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;:::::::ccccccccclllllllllllooooooddddddddddxdooooolllllllllooooooodddddddddddxxxxxxxxxxxkkkkkxxddxxdddddoooddooooolllllcccc::::;;;;;;;;::::c::;;;:::;;;;;;;;;;;;,,,,,,'''''',:c::::ccclcccccccccccccccccccccc:::::::::::::::::::;;:::;;;;;;;;;;:;;;;;,,,;\r\n" + //
                    "'''',,,,,,,,,,,,,,,,;,,;;::;;;;;;;;;;;;::::;;;::;::::::::cccccccccllllllllloooooddddddddddxxxxxxxxxxxxdolllooooloooooddddddxxxxdxxxxxxxxxxxkkkkkxxxxdddddddddddoooooolllllcccc::::::;;;;:::::cc:::::;;;;;;,;;;;;,,,,,,'',,,,,::cllllllllllcccccllllllccccccccccccccccccc::ccccccc::::::::::;;;;;;;:;;;;;;;;;\r\n" + //
                    ",,,,,,,,,,,,,,,,,;;;;;;,,;;;;::::::::::::::::::::::::cccccccclllllllooooooooddddddddxxxxxxxxxxxxxkkkkkxdooooooolooooodddddddddxxxxxxxxxxxxkkkkkkxxxxxddddxxdddollloolllllcccccccc::::::::::;::::::::;;;;;;,,,,,,,,,,;;;;:ccccloolllllolllllllllllllllcccccccccccccccccccccccccccccccccc::::;;::::::;;;:;;;;;\r\n" + //
                    ",,,,,,,,;;;;,,,;;;;;;;;:;;::::::::::::::::::cccc::::ccccccclllllooooooooddddddxxdddxxxxxxxxkkkkkkkkkkkkkkkxdooodddddddddddddddxxxxxxxxxxxxkkkkkkkxxkkxxxxxdddollllooollllllcccccccc::::;::::::::::::;;;;;,,,,,,,;clloooooddoodooooooooolllllllllllllllllcccclccllccllllllccccccccccccccc::::::::::::::::::::\r\n" + //
                    ";;;,,,,,;;;;;;;;:::::;;:::::::::::::ccccccccccccccccccccllllllloooooooodddxxddxxxxxxxkxxxxkkkkkkkkkkkOOOOOOkxxxkkkxdddddxxxddddddxxxxxxxxkkkkkkkkkkkxxxkxxdoollllllooolllllcccccccc::::;;;;;;:;;;;::;;;;;,,,,,',;ldddxxdddddddooooddooooooooollllllllllllcclllllllllllllllllllllllllllccccccc::c:cccc:::::::\r\n" + //
                    ";;;;;;;,,;;;;;;;:::::::::::::::::::ccccccccccccccccccllllllolloooooooddddxxxxxxxxxkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOkxxxkkkxddddddxxxxxxxxxxxkkkkkkkxxxxxxdolllccclllloolllcccccccccc:::::::;;::;;;;;;;;;;,,,,,,'',coooxxxdxxxxxddddddddddddddooooooooollllllllllllllllllllllooollllllllllcccccccccllccccccccc\r\n" + //
                    ";;;;;;;;;;;;;;;;:::::::::c:::c:::ccccccccccccccccllllllllllllllooooodddddxxxxdxxxxkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOkkkxxxxxxxxdddxxxxxxxxkxxxxxxddoolccccclllllllllllccccccc::::::::::::;;;;;;;;;,,,,',,,,,,:clodxxxxxxxxxdddxxddddddddddooooooooooolllllllloolllllllooooolllllllllllllcccccclccccccccc\r\n" + //
                    ";;;;;;;;;;;;;;;:::::::::cccccccccccccccllcclllllllllllllllllllooooodddddddxxddxxxxxxxxkkkkkOOOOOOOOOOOOOOOOOOOOO0000000000OOkkkkkxddodddddxxxxxxxxxddoolllllccllllooollllcccccccccccc::;;;;::;;;;;,,,,,,,,',,,'',;:cldxxxkkxxxxxdddddddddddddddddooodooooollcclooooooooooooooooollllllllllllllllllllllllclll\r\n" + //
                    ";;;;;;;;;;;;;::::c::::::cccccccccclllccccccclllcllllllllloooooooooddddddxxxxddxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOOO000O0000000OOkkkxxoolooddddxxxxxxdddollloolccllllooooollllcccccccc:::::;;;;;:;;;;;,,,,,,,''',,'',;;:ldxkkxxxxxxddddddddddddddddddoooddoooooooooooooooooooooooooooloooolllooolllloolllllllodx\r\n" + //
                    ",,;;;;;;;;;::::::::c::::cccccccccclllllllccllllllllllllllloolloooodddddddxxddxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOO000000OOO00000OOkxdoooooooooddxxxxddoolllloolllooooooolllllllcccc:::::::::;;;;;;;;;,,,,;,,,',,,,,,,;::cldxxxxxxxxdddddddddxxxxxxddddoddddddxxkxxdddddoooooodddddoooooooolllloooolooooolloodddd\r\n" + //
                    ";,;;;;::;:::::::::cccccccccccccclccclllllllllllllllllllllloolloooddddddxxxxxxxxxxkkkkkkkkkkkOkkkkOOOOOOOOOOOOO000000000000000Okdooooooooooodxxdddoollccllllllllooollllllllcccc::::::::::;;;;;;;;,,,,,,,,,,,,,,;;::::::coxxkxxxxkkkxddxxkkkkkxxxxkkkkkkxxxxxxxxxxxxddddddddxdddddddddollodxOOkxdooolooooddoc:\r\n" + //
                    "::::;::c::cclllcccoooolllllcllllllllllllloolllllllllllllooooooooodddddxxxddxxxxxxkkkkkkkkkkkkkkkkOOOOOOOOOOOOO0000000000000Okxddoooooooooooodddoooollllllllllllooollllollllcccc:::::::;:::;;;;;,,,,,,,,,,,;;;;;::;;:llodxxkkkxkkkxxxxxkxxxxxxxxxxxxxxxdddooooddddxxxxxdoodddxxxddoooodxkO00Oxooolllllllooc::\r\n" + //
                    "cllllooooooddoooodxdlclooooooddoooooooooddddoooolollllldxkxdlloooodddodddddddxxxxkkkkkkxxkkkkkkkkkkkOOOO00OOOOOOOOOO0000000kdooooooooooooooodddooollloooooolllllllllloollllllcc::::ccclodoc;;;:::;;,,,,,,;::;:cllloddxkkkkkOkkkkkkxxkkkxxxxddddddddddddooooooooooooddddoooooooooxxddxkkkkxdolldxdddolclc:;,,\r\n" + //
                    "ddxxxkkdlodxdooxxxxxocclodooddddodddddoooodoooooddddooodxxxdddxkxxxxxdxxkkkkxxxkkOOkkkkkkkkkOOOkkOOOOOO000000000OOO000KK00Oxddddooodoooooooooodddoolllllloolllllllccllllcccllc:c::cdkOO0Okdc::lddlc:::cccclllloddxxxkkxxxxxxxdddxdddddddddddddxddxdddddoooooooooooddxxxkkxxxxxxkOOOOOkkkxolcldxddxdoollc:;'.\r\n" + //
                    "ddddddddodxxxdxkkkOOkdooddocloolllooooolllooodddddxxxdooddxxxkOkkkkxxxkOOOOkkxkkkkkkkkOkkkkkkOOkkOOOOkkkOOOO000000OO0KKKK0Oxxxxxxxddoooooooooooodoooooolllllllllccccccclcccccc:::cdO00K000OxdoodxxdoodddoooooooooddddddooooooolloolllloooooolooooooollllllllllllllooddxxkkkkOOkkOOOkxkkxxxxxxddollclllc:;,'.\r\n" + //
                    "odooodxxxxxxxxkkkxkkOkkkxddxkxxdooolllllllllllloooooooooodddddxxxdoddxkkxddxkkOOkkkkkOOOOkkkkkOOkOOOOOOOO00OO0KKKKKKXXXKKKKOOOOOOOkddooooooooooooodddoooollllllccccccccccccc:::::cx0KKKK00K000OOOOOkkOOkkkxxxxxxdxkxdodddxdoooooloodollooooooooodddooollllloooodxxxxddxkkkkkkkxxkkxxdoooooooolllc::;;;,,,'..\r\n" + //
                    "dxxkxxxxdooollooooodxxxxddodxxdddollcccccccccccc:ccccccloooodxxxxxxkkkkkxxkOOOOOO0OOOO000000OO0OO00000000KKK00KKKKKK00KKKKKK000K00Okxdoooooooooooooddooooolllcccccccccccccc:cc::;;oOKK0OOO0OO00OOO0000kxxkOOOkkOOOOOOOOOOOkxxxkkkkkkxxxxxxxxxxxkkkkxxdoddoloxxddxxxxxkOOOOkkxxxxdoodxdlllclllc:::;,,,'''''..\r\n" + //
                    "ddxxxxxxdlc::,,,;;,;;:cl:;:::ccccc::::::::::;;::::::::ccccclloooodxkkkOOOOOOOOOkkOOOOOOO00KK0OOOOOOOOOO00O000000OOOkkkOO0000OO00OOOOkxdooooooooooooooooooolllccccccccccccc::::::;:lkOOkO00OkkkkOkkO0000OOkkkkkxxxkOOOkkkkxdddxxxxxddddxxxxdxxxxkxdddooddddxxxddxkkxkkkOOkkkkkkkkxxxdolllccccc:::;;,,'''.....\r\n" + //
                    "llolcldkkkdool:::;,'.,:cc::;,;,,;;;;;;;;;;;;;;;;;;;;::::::::ccccllodddddddddxk000OOO000000KXK00OOOkkkkkOOOOO00OOOkkkkOOOkkOOOkkkkkOOkxxdddoooooooooooooollllllccccccccc::cc::::::;:okkOKXKKKKKXK000OOO00000000Okk0KK0Okdodxxdoolllllllloooooollllcllccllllooooddddoddddoooddddddddollllcccccc::::::::;,,,,,,\r\n" + //
                    "oloddddxxkxdxkkkxdl::lddddooolllol:;;;;;;;;;;;;;;;;;;:;;:::codolldkkkkkxxdxdxOKKKKKKKKKKKKK0OOO00OOkkkO000OO000OOkOO000OOOOO0Okkkkkkkxddoddooooooollloooollcccccc:::ccc:::c::;;;;;cdO0KKKXXXXNNXXXXKKKKK00KKKKKKK000KK0OOO00Oxdoloolclooolldddooolccclllllolcccccccccccccccccccccccccccc:::::::::ccc:;;:clcc\r\n" + //
                    "oooodxxdddddxkOkkxxxxdollclxOkxxxdl:;:::;;;;;;;;;;;::;;:clodxxxdxOOkOOkddxkOOO0000KKKKXKK0OOOOOOOOOOOO0OOOkkkkO00O0000OOOOOOOkkkkxxxxxddddddoooooollllllllcccccc:::::::::::::;;;;:okO0KKKKXXXKKKKXKK0O000000000OOOOO00KKOxxkO00OOOkkxkkkxddxkxdxkkddodxdddolc:::clcccoooddl:::::::::::::::::::::::;;;;;;;;;;\r\n" + //
                    "llccloc:coddxdooodddxolcccodxdoloolc:::cc::;;;;;;;;::;:cclollclloooloollloodxkkOOO0KKKK00OOOOO00OOkOO00K0OkkOO0KKKKK00O0000OOkkkkxdddxxdddddooooooolllllllcccccc:::c::::::::;;;;;;coxO0K00KKKK0000OkxddxkkkkkkkOOOOOOOkkdodxO0OkxxxkOOxxxxxxxxxkkkkkOkkxxddollcccccclooooolccccc::::;:::::::::::;;;;;;;;;;;,\r\n" + //
                    ":c::;;,;:oooooooooc:cllc;::coddlc:cccccccllccccc:::::c::::::ccccccccllclllllooddodxkOOOO0000OOOOOOOO00KK0OO000KKKKKKKKKKKKK000000Oxddddddddddoooooooooolllccccccc:::::::::;;;;;;:::cldxxxxxkOOkkxdolllloddoodxkkxxxdddddxdxxxdolloodxxoollolllooooodkkxxdollllccccccllccc::cccc::::;;;::;;;:;;;;;;;;;;;;;;;;\r\n" + //
                    ".'''',:cccc:::lddolclol:;,,,;::cccloooooddol::cloxxddocccccccc:::::cccc:ccccccllloxdddddxxkkxddddxxxxkkxkOO0000OOO00KKXKKKKKK00KK0kxddddddxxdoooooooooollllccccc::::::::::;;;;;;;;;:clllllllloollllllllllllllooollllllllllllllccccccccccccccc::ccllodoolcc:::clc::::::ccllllc:::;;:;;;;;,,;;;;;;,,;;;;;;;;;;\r\n" + //
                    ".....';::;;;;::::cclc:,,''','''',;;;;:ccllc::coddxdooolllc::;::;;::;::::::::::cccclcclllcccclloooooooodddxxxxkxxxxxkOOOOOOO0OOOOOkxxxxxdddddooooooolllllllccccc::::cc:::::;;:;;:::clllllllolllllcllllllcccllcccccclccclcccccc::::::clodxocclolccoxkkxddxxxdodxxxdl:cldxxlc:coddl;;;;;;;;,,,,,,,,,,,;;;;;;;;:\r\n" + //
                    ".......''''''''..',;,''....''...',,,',,,,,,;;;:::;;;;;:;;;;,,;;;;;;;;:::;;;;;::::::::ccccccccllllllooooooooooooooooddddxxxxxxxxxxxxkOOOkxxddddddooolllllcccccccccccc:::::::::::::cloooooooolllllllllllllcclllcccccllllccccccclodxkkkO0K0OOO00OkkkkkkxxOKKKKKXKK00OOO00KXKOxxxdol:;;,,;,,,,;;;;;;;;;;;;;;;;;:\r\n" + //
                    "...........''.......'''''.'''''''''''''''',,,,,,,,,,,,,,,,,',,;;;;;;;:::::::::::c:cccccccccllllloloooooooooodoooooddddddxddxxxxxxkO0KK0Okxddddddoooollllllccccccccc::::::::::cc:cloooooooooooooolllllllllllllccclllllllcccclllodxxxddxxxxkkkxxxxxkO00KKXXXXK0kkO00O00K00OkkkOkolllcllcccc;;;;:;;,;;;;;;;;;;;\r\n" + //
                    ".....................'''''''''''''''''''''''''''',,'',,''''',,,,;,,;;;;;::::::ccccccccccclllllllllloooooooooddoddddddddddxxxxxkkkO0KXK0Okxdddddoooooolooolllccllcccc::::::::::ccllooooodddddddooolllollllllllllllllllllccclllccccc:cccccccclllllodxk00KKKKKK0kkO00OO00OxdxxxO00OkOOOOOkOOxl;;;;;;,,;;;;;;;;:\r\n" + //
                    ".................'........''''.''''',,''''''''''',,,,,,,,,,,,,,;,,,;;;;;;::::cccccccclcclllllllllllooooooooodddddddddxxxxxxxkkkOO00000OOkxxdxddddoooollllllllllllcc::::::::::clloooloooddddddddoooooooolllllllllcccccccccccc:::cc::::::::::c:::coxkO0OOO0K0kddxkxxkO0KK0Okkkk0Okk0KOkO00Okxdoolc:;:::;;;::::\r\n" + //
                    "......','..................'''''''''',''''',,,,,',,,,,,,,,,;;;;;,,;;;;:;;::::::::::clllllooooolllllooooooddddxxxxxxxxxkkkkkkkOOOOkkkkkkkkxxxdddddoooolllllllllllllccccccc::cccloooooodddddoodddddoodoooolllloolllllccccccccccccc:::cc:cllllloolccoxkkxxkxxdodxkdlok00OO00OOK0Odclooolodxk0KXKKK00OOOOxoc::::\r\n" + //
                    "...',,','................''''',,''''',,,,,,,,,,,,,,,,;;;:::::::;:::::::::ccc::cc:cclooodddddddddddddxxxxxxkxxkkkkkkkkkOOOOOOO0OOOkkkkkxkkkxxxdddoooollllllllooolllllllcccccccldxxdddddxxddddxxddddddoodddoooooooooooooolllllllllcclccclodddddoodoccoxdlcc::looolcodxdlodxxxkkkxolcllclx00KXKKKK000OkO0Ooc:::\r\n" + //
                    "',;:cccc;'...',::;,'''''',,,;,,,,;,,,,;;;;;;;;;;::::::::::::::::ccccccccllllccllllloooodddddddddxxxxxxkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOkkkkkkkkxxddoooolllllloooooollllllccccclodxOOOkkkxxxxxxxxkkk00OOOOkxdoooooooooooooolloolllllcccccccodlcddokK0xx0XKxl;,,,,;;;;::cc:;:c::c::codxkOkk00OOKKKKOkkO000KKko:::\r\n" + //
                    ":ldkOOOkdlc::loxdl:;:;,,;;;;;;,;;;;;;;;;:::::::::::;::::::::::::::cccccccllllllooollooodddddxxddxxxxxxxkkkkkkkkkkkOOO0KXXKK0000000000OOOOOOOkxxdooooolllloddooooolllllllcllllodOXXNNXKKKK0OOKXXXXKKXXXXKkxk0000koloddoolllcldxkxdolc:cllldOKKKKKKKXXXK0xc;,;;,,,,;:oxdoddc;;;;:dOOOOOkkkkkkkkOO0KXX0Okkkdlc:\r\n" + //
                    "oxkOOOxl::loodoolccldoc;,,;;;,,,,,,,,,,,;;;;;;;;,,,,,;;;,,,,;;,;;;;::cccccclllllooooooddddddxxxxxxkkkkkkkkkkOOOO0000KXNWWNNNXXKXXXXXXXXKKKK0Okddooddoooooodddddddooooollllllclx0KXXNNNNNNNNNNXKOOkO0KKXNXXXK0OkkkkkkxdoodddkKXKKK0kddkOOkOKK000OO0KOxdddddool:coxxdddxkxoc;;;;:looooodxddolcc:cdxkxkxdoooodx\r\n" + //
                    "xdkOOxdoccldxxxOkkkO0Okoodo:,,,''''''''','''''',,,,,,,,,,,,,,,,,,,;;;::::ccccccccclllooddxxxxxxxxOOOkO00KKKXXXXXXNNNNNNNNNNWWWWWWNNNWWWNNNNXK0kddoooooooddddxkkkxddddoooollcccdO0KKXXXXXXXXNXXK0OkkO00KXNNNKkdodOK0000OO000KKKKKKKK000KKKKK0Okxddxdlc::lxO00OOO0KKK0kOOOOkdl:;,;;;;,;:cccc:,,:oxoc;:ccclox0K\r\n" + //
                    "ccooc;:ooloooxOOO0000Okkkxdc;''..''''',,,''''',,,''',,,,,,,,,,,,,;;;;;:cccclloooooddxkOKKXXKKKKKKXXKKXXNNNNNNNXXXXXXNNNNNNWWWWWNNNNNWWWWWNNNNX0kdddddddddddxO00OOkkkkxxxxdolodxOKXXNNNNNXNNXXXNXXKK00KXXXNNNX000KXXXXXXXXXK00KKK0000OO0KK00KXXKK0OxddxkOKXXKKKK00KKKKXNNNNNKkdc;,;;;;codollldOKK0xl;,;cdxxdd\r\n" + //
                    "lc;'..,clc;',colldkkkkkxo:;;,''...',,,,,,,,'',,''''''',;;::clooooollodxxxxxxkkkkkkOOOO00KKKXXNNNNNNNNNNWWWWWWNNNNXXNNNNNNNNNWWWNNNNNWWWWWNNWNX0xoodkOOkkkxxk0KK000OOkkkkkkkxxxk0XNNNNNNXXXXXXXXKKKKKKKXXXNNNNNXXXXKKKXXXXXXXXXKOkk0KKKKKKKXNNNNNNNXKKXKKXXXXKKKXK00KXXKKXXKK00Okxkxl;,:odxkO000K0kl,';:;;,,,\r\n" + //
                    ";...  .,::,;clc;;:looolllc;,''',;;:cc::;,''',,;;:clllooxxkOO00KKKXXKXXXXXXKXXXKKKKK00KKKKKKXXXNNXNNNNNNNNNNNNNWNNNXXXXXNNNNNNNNNNNNNNNNNNNNNNNKkddxkOOO0K0OO0KKK00OkxxkO000000KXNXXNNNXXXXXNNNXXK00kxkOKKKKKXXXXK0O00KXXXXXXXXXKO0XXXXXX000000XXX0kxk0K0000K0kddxO00OxdodxxkkxxkOkdoc;,';okOdldxdddlcodlc:cc\r\n" + //
                    "...    ...':lc'..',,,,;:ccccc;;;cldolc:;::clodxxkkkOOkkkkO00000KKKKKKKKKKXXXNNNNNNNNNNNNNNNNNNNNNXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNXXXXXXKKKK0OOO0000OkxddxOKKKXNXXKKKKKXXXXNNNNNNXKKXX0OkkxxkO0KXXK0kkO0KXK0OO0KKXXNNXXXKKK0OOkdodxdl:;coddxxdoc:;;:oxdool:,,;:cllllldkkdc:loxkoldoccxOOOOO0000\r\n" + //
                    "..     ................',,,;;,'.',;;,''',;;::cclllccloodxkkkOOOkOOOOOOO00KKKXXXXXXXXXXXXXKXXXXXXXKKKKKKKKKKKKKXXXXXXNNXXXKK00KKXXXXXKKKXXXNNNNNNNNXXXKK0kkkOOkkkxxdddxO0KKKKXKKKXXXXXXXXXXXXXXXKKK00000xddddxxxxooxOKXKOxoodddxkOkkkkOOkxxkdlc:::;,,,:odoc;;,,,,cxOxl:;,',;cllc;;;clolcclllllodl;:dkkO0OkkOk\r\n" + //
                    "        .. .......................''''',;;;;;:;,,,'',,;;;::::::cccclloxO0KXKK0000000000OO000KKKK0000K00000000KKKKXXXXXXXXK00OO000KKK00000KKKXXXKKXXXX00OkOKXKKOkxdddk0KXKKKXXKKKXXNNXXXXKOkkO0KXKK0KXNX0OkkkOOxoox0XXKKKK0K0xc:cllccloxdlol::;,'''.'cdOOo:;,,,,;cool:;,,,:llc;,''''''',,,,;:cool:clc:::;;;;;\r\n" + //
                    "           ... .................''''''',;:loxdc;'..'.'''.';cclllccokkO0KKKKK0kddkkkkOOOOO00OO0000000KKK000OOkkkOO00KXXXX0OkkxxdxkOKK00KK000000KKKXNNXKKKKXNXXXKOOOOO0KKKK0KXXK00KXXK0000kdooxO00O0KXNXXXXXXNNXXKKXNN0kkKXKKK0xodOOddkO00Oxl;,,'....'lkkdodoc;,,,,,'',,,'',,,''....'''''''',,,,;,,,,,'''.''''\r\n" + //
                    "            ..........',,'...............'';cc:,'.........':ok00K00OkOOkddxOOkxxxxk0KKXXXKXK0OO00kkkkkO0KK0OOkxkkkxdxxxoc;,;;;:lkKNKKKXXXXKKKKXXNNNNXXXXNNNXKKKX0OOOOO0000000OO00OkkkkkxddoolodkOO0KK000KXNXXXXKKKK0xoldxddxxox0Kkoloolll:;,,'''''',coollooc:;,''''''''''''.......'''.....''''''''..........\r\n" + //
                    "              ...............................','........',,;:cdkkxoooxOkxdxkkkOOO0KKXXKKKKXXXKOOkxdoodx0XKKKOxc:::;'.''''......':dOKKKXXXNNNNXXXNNNNXXNNNNNNXOkxl;,,,:d0KKKXK0Okxdxxddddoolccok0OOOOOOOOKXK0OOkxddkkkxddoclllx0KOoc::,,,,,,'''...'''',,,,,,,,,''''''''''''..................................\r\n" + //
                    "        .................................''...''''.....;dkOxollll::ccd0K0OkkkO0KKXXXXKKKXXXKKK00OxdoxOKXNNN0o:,...................';;:lx0KKXNXKKKXXXNNNNNN0dc:,'..''..,ok0K0OkkkkO0000KK0dc:cclooooxk00Okxdlcccccok00Odlc:::cdxdlcldxddoc;'...................''.'''.'''''..................................\r\n" + //
                    "  ....................................'''''''',,''';::lxkxoodxxoccccccodxxxxkkOKXXXKKKKKKXK000KXK0OkO0KXXNNOo:;,'.. ..'.......   ......':oddkKNNXNNNNNNWNk:'............,lk0OkO00KKK00OOdl:::::::::lodolc::::::::clolc:;;;;,;;;;;;:loool:,'.'...............................................................\r\n" + //
                    "...................................'...'''''''',,,;:cllc:;,',;;;;;;::;;;cokOO0KXXK00000KKKKOxkOO0KXKOk0XNWNKkol:,'..',;,''.....      ...'''',ckKNXkooxO00l'..............,dXWNNNNX0xoollc::::::;;;;;;;;;;;;;;;;;;:::;;;;;;,,,,,',,,'''''''..'...............................................................\r\n" + //
                    ".................................'',,''''''''',,,,;,,,'''''''''',,;;;;;,;lk0KK00OxxO00KKKKKK0K00KKKKOO0NWNNNKOoc:;;;;;;;,.........    .,'....',cdl,..';:c:'...............,xNWNX00Oxlcccc::::::;;;;;;;;,,;;,,,,,,,;;,,,,,,'''''''''.........................................................................\r\n" + //
                    "..................................',,'''''''''''''''''..'''''',,,'',,,,;::coddolcclddxkO000KKKK0OxxddxO0000XN0dc;;::;,'''..........  .',''....'',,...........''..  ........o00kkkxkOdc::;;;;;::;;;;;;,,,,;;;,,,,,,,,,'''''''''''...........................................................................'\r\n" + //
                    "................................................''.......''''',,',,,,,,,:codoc;;;codolloxkO0000OxollokKXKKXNNkc;,,;cc:;'......'.......,::;,'....''.......'...........'.....,ll:;,,:l:,,;,,;;;;;;;;;;,,,',,,,''''',,,''''..........................................................................'''''''',,\r\n" + //
                    " .............................................................''''''''',,,;;;,,,;:clcc::clodxxxdlllclONNNNWWKxl:,',:cc;'...........'...,;;,,''...'..........''........... ...,,,'.......',,,,,,,,,,,,''''''''''''',,'..................................................................'''''',,,'',''''''',,\r\n" + //
                    "   ..................    ......................................''''',,,',,',,,,,,,,,;;;;;:::::::::::dKNNNNNNKxc,'..',;::;'......''........,;;,,,',,'.......''............................',,,,,,,',''''''''''''''','''.............................................................''''''''''''''''''.''''''\r\n" + //
                    "     ...                          .  .........................'''''''''''''',,''',,,,,,,;;;;;;;;;;;ckXXKKNNXOo;'......';:;,'.'..,:,.,;,'..'',,,,,,,'.... ...'............................'',,,,''''''''''''''''''''''''''''......''''..........''''''''..'''''''''''''''...........'''''''''''''''''''''''''\r\n" + //
                    "  .....                          ................................'''........'''.''''',,,,,,,,;;,,;:d0OOkxO0Odc:;'..   .';;;,,,'',:;;;::,'''.......'........................ .............'',,,,''''''''''.''''''',,,,,,,,,,,,,,,,,,,,,,'''...',,,,,,;;,,,,,,,,,,,''''''.........''''''',,,,'''''''''''''''''\r\n" + //
                    "....... ....                        .........................................'...''''',,,,,,,,,,,,cxOoccldxxoll:;'...  .'''.','.',;;,,,...'''''............................   ...........'',,;;;,,,,,,,,,,,,;;,,;;;;;;;,,,,,,,,,,,,,,,,,'''''',,,,,,;;;;,,,,,,'''''''''...........''''',,''''''''''''...''''\r\n" + //
                    "  ...    ................  ..................................................'..'''''''',,,,,,,;,,cxxl;;lOOo::cc:,... .';;,'....'''''.....'''','..........  ...............        ......',::;:::::::;;;:;;:::;;;;;;;;;,,,,'',,,,,,''''''...'',,,,,,,,,,''''',,,'''''''.........................''''....''''\r\n" + //
                    "         ..............................................'................''''''''''''',,,,,,,,,;;;;:lolc:codc,';cc:;;,,,;,,;;'...',',,''',;;'',;,'........  ..........'...         .........;,'';::::::;;;;;;;;;,,;;,,,;,,,,''''''''''........',,,,,,,'''''''',,,'''''''............................'....''''\r\n" + //
                    "       ....................................'''''.''''',,,'''''''''''.'',,,,,,,,,;;;;::::::::::ccccclllc;;:::;,,;:::;:ccc;,,,'....',;;,'',:::;::;'....................''.      ................';::;;;;;;;;;;;;,,,,,,,,,,,,,'''''''...........'',,,,'''''''..''''''''''....................................''\r\n" + //
                    "           ................................''''''''''''''''''''''',,,,,,,,,,,,,,,;;;;::cccccccccccccccc:::ccc:;;;,,,,;:clc:;;,. ...,:;,,,;::::c:,...'''.......''...''''...    ...      ......',;;;;;;;;,,,,;;;;,,,,,,,,,,''''''''............'''',,,,,,,,'''.'''''''''...........................''.........\r\n" + //
                    "           ................................'''''...........'''''''',,,,,,,,,;;;;,,;;;;:::cc:::ccccccccccccccc::;;,''.':cc:;;;,''''..',,;;;;;;cc:,'''''''.....'''...''''.........        .....''''',,,,,,,,,,,,,,,,,,,,''''''''................''''',,;,,,''....'''..........................................\r\n" + //
                    "                ............................................''..''''',,,,,,,;;;,,,,;;;;:::::::ccc:::::c:cccccc:::;,'..';:::;,,,,,'.....',,..';;,'','.....'''''''''''..........     ..........'..........',,,,,,,,,''''''......................''''',,;;;;,'....''.....'',,,,,'..............................\r\n" + //
                    "                 ... ......................................'''...'''',,,,,,,;;,,,,;;;;;;::::::c::::::::::cclllcccc:,'.',:lcc:;,,,,'....... .',,..'''......''''',,,''.........     ..........,;'.'..''''.',,,,,,',,,''''''...''''..............''''',;;;;;;,'.....'...'',;:::;,.............................'");
        }
        else {
            throw new IllegalArgumentException("This city does not exists, verify if it didn't take any nuclear bomb");
        }
    }
}
